#!/bin/bash
# Backup the /etc/hosts file

cp /etc/hosts ~/hosts.new
sed -i '/127.0.0.1\s\+localhost/c\127.0.0.2\tlocalhost' ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts